-- LE NOMBRE DE VENTE DE PRODUITS
WITH ANNEE_DISTINCTE AS (
    SELECT
        DISTINCT EXTRACT(YEAR FROM DATE_COMMANDE) AS ANNEE
    FROM
        COMMANDE
), MOIS_ANNEE AS (
    SELECT
        GENERATE_SERIES(1, 12) AS MOIS,
        ANNEE
    FROM
        ANNEE_DISTINCTE
)
SELECT
    P.ID                                             AS ID_PRODUIT,
    P.ID_UNITE                                       AS ID_UNITE,
    COALESCE(SUM(CP.QUANTITE), 0)                    AS TOTAL_VENDUS,
    COALESCE(SUM(CP.PRIX_UNITAIRE * CP.QUANTITE), 0) AS TOTAL_VENTES,
    MA.MOIS                                          AS MOIS,
    MA.ANNEE                                         AS ANNEE
FROM
    MOIS_ANNEE       MA
    LEFT JOIN COMMANDE C
    ON EXTRACT(MONTH FROM C.DATE_COMMANDE) = MA.MOIS
    AND EXTRACT(YEAR FROM C.DATE_COMMANDE) = MA.ANNEE
    LEFT JOIN COMMANDE_PRODUIT CP
    ON CP.ID_COMMANDE = C.ID
    AND CP.ID_PRODUIT = 1
    LEFT JOIN PRODUIT P
    ON CP.ID_PRODUIT = P.ID
    OR P.ID IS NULL
WHERE
    MA.ANNEE = 2024
    AND ((CP.STATUS_COMMANDE >= 1)
    OR P.ID IS NULL
    OR C.ID IS NULL)
GROUP BY
    P.ID,
    P.ID_UNITE,
    MA.MOIS,
    MA.ANNEE
ORDER BY
    MA.ANNEE,
    MA.MOIS;

-- LE NOMBRE DE VENTE POUR TOUS LES PRODUITS D'UN VENDEUR
WITH ANNEE_DISTINCTE AS (
    SELECT
        DISTINCT EXTRACT(YEAR FROM DATE_COMMANDE) AS ANNEE
    FROM
        COMMANDE
), MOIS_ANNEE AS (
    SELECT
        GENERATE_SERIES(1, 12) AS MOIS,
        ANNEE
    FROM
        ANNEE_DISTINCTE
)
SELECT
    COALESCE(SUM(
        CASE
            WHEN P.ID_PERSONNE = 1 THEN
                CP.PRIX_UNITAIRE * CP.QUANTITE
            ELSE
                0
        END), 0) AS TOTAL_VENTES,
    MA.MOIS      AS MOIS,
    MA.ANNEE     AS ANNEE
FROM
    MOIS_ANNEE       MA
    LEFT JOIN COMMANDE C
    ON EXTRACT(MONTH FROM C.DATE_COMMANDE) = MA.MOIS
    AND EXTRACT(YEAR FROM C.DATE_COMMANDE) = MA.ANNEE
    LEFT JOIN COMMANDE_PRODUIT CP
    ON CP.ID_COMMANDE = C.ID
    AND CP.STATUS_COMMANDE >= 1
    LEFT JOIN PRODUIT P
    ON CP.ID_PRODUIT = P.ID
WHERE
    MA.ANNEE = 2024
GROUP BY
    MA.MOIS,
    MA.ANNEE
ORDER BY
    MA.ANNEE,
    MA.MOIS;

-- LE NOMBRE DE VENTE POUR UN PRODUIT PRECIS
-- WITH ANNEE_DISTINCTE AS (
--     SELECT
--         DISTINCT EXTRACT(YEAR FROM DATE_COMMANDE) AS ANNEE
--     FROM
--         COMMANDE
-- ), MOIS_ANNEE AS (
--     SELECT
--         GENERATE_SERIES(1,
--         12) AS MOIS,
--         ANNEE
--     FROM
--         ANNEE_DISTINCTE
-- )
-- SELECT
--     P.ID AS ID_PRODUIT,
--     P.ID_UNITE AS ID_UNITE,
--     COALESCE(SUM(CP.QUANTITE),
--     0) AS TOTAL_VENDUS,
--     COALESCE(SUM(CP.PRIX_UNITAIRE * CP.QUANTITE),
--     0) AS TOTAL_VENTES,
--     MA.MOIS AS MOIS,
--     MA.ANNEE AS ANNEE
-- FROM
--     MOIS_ANNEE MA
--     LEFT JOIN COMMANDE C
--     ON EXTRACT(MONTH FROM C.DATE_COMMANDE) = MA.MOIS
--     AND EXTRACT(YEAR FROM C.DATE_COMMANDE) = MA.ANNEE
--     LEFT JOIN COMMANDE_PRODUIT CP
--     ON CP.ID_COMMANDE = C.ID TAND CP.ID_PRODUIT = 1 LEFT
--     JOIN PRODUIT P TON CP.ID_PRODUIT = P.ID
--     OR P.ID IS NULL
-- WHERE
--     TMA.ANNEE = 2024
--     AND ((CP.STATUS_COMMANDE >= 1)
--     OR P.ID IS NULL
--     OR C.ID IS NULL)
-- GROUP BY
--     P.ID,
--     P.ID_UNITE,
--     MA.MOIS,
--     MA.ANNEE
-- ORDER BY
--     MA.ANNEE,
--     MA.MOIS;


-- WITH ANNEE_DISTINCTE AS (
--     SELECT
--         DISTINCT EXTRACT(YEAR FROM DATE_COMMANDE) AS ANNEE
--     FROM
--         COMMANDE
-- ), MOIS_ANNEE AS (
--     SELECT
--         GENERATE_SERIES(1, 12) AS MOIS,
--         ANNEE
--     FROM
--         ANNEE_DISTINCTE
-- )
-- SELECT
--     COALESCE(SUM(
--         CASE
--             WHEN CP.ID_PRODUIT = 1 THEN
--                 CP.PRIX_UNITAIRE * CP.QUANTITE
--             ELSE
--                 0
--         END), 0) AS TOTAL_VENTES,
--     MA.MOIS      AS MOIS,
--     MA.ANNEE     AS ANNEE
-- FROM
--     MOIS_ANNEE       MA
--     LEFT JOIN COMMANDE C
--     ON EXTRACT(MONTH FROM C.DATE_COMMANDE) = MA.MOIS
--     AND EXTRACT(YEAR FROM C.DATE_COMMANDE) = MA.ANNEE
--     LEFT JOIN COMMANDE_PRODUIT CP
--     ON CP.ID_COMMANDE = C.ID
--     AND CP.STATUS_COMMANDE >= 1
--     LEFT JOIN PRODUIT P
--     ON CP.ID_PRODUIT = P.ID
-- WHERE
--     MA.ANNEE = 2024
-- GROUP BY
--     MA.MOIS,
--     MA.ANNEE
-- ORDER BY
--     MA.ANNEE,
--     MA.MOIS;

WITH ANNEE_DISTINCTE AS (
    SELECT
        DISTINCT EXTRACT(YEAR FROM DATE_COMMANDE) AS ANNEE
    FROM
        COMMANDE
), MOIS_ANNEE AS (
    SELECT
        GENERATE_SERIES(1, 12) AS MOIS,
        ANNEE
    FROM
        ANNEE_DISTINCTE
)
SELECT
    P.ID                                             AS ID_PRODUIT,
    P.ID_UNITE                                       AS ID_UNITE,
    COALESCE(SUM(CP.QUANTITE), 0)                    AS TOTAL_VENDUS,
    COALESCE(SUM(CP.PRIX_UNITAIRE * CP.QUANTITE), 0) AS TOTAL_VENTES,
    MA.MOIS                                          AS MOIS,
    MA.ANNEE                                         AS ANNEE
FROM
    MOIS_ANNEE       MA
    LEFT JOIN COMMANDE C
    ON EXTRACT(MONTH FROM C.DATE_COMMANDE) = MA.MOIS
    AND EXTRACT(YEAR FROM C.DATE_COMMANDE) = MA.ANNEE
    LEFT JOIN COMMANDE_PRODUIT CP
    ON CP.ID_COMMANDE = C.ID
    AND CP.STATUS_COMMANDE >= 1
    LEFT JOIN PRODUIT P
    ON CP.ID_PRODUIT = P.ID
WHERE
    MA.ANNEE = 2024
    AND P.ID = 1
GROUP BY
    P.ID,
    P.ID_UNITE,
    MA.MOIS,
    MA.ANNEE
ORDER BY
    MA.ANNEE,
    MA.MOIS;

-- LA LISTE DES ANNEES OU IL Y A UNE OU PLUSIEURS COMMANDES
WITH ANNEE_DISTINCTE AS (
    SELECT
        DISTINCT EXTRACT(YEAR FROM DATE_COMMANDE) AS ANNEE
    FROM
        COMMANDE
), MOIS_ANNEE AS (
    SELECT
        GENERATE_SERIES(1, 12) AS MOIS,
        ANNEE
    FROM
        ANNEE_DISTINCTE
)
SELECT
    DISTINCT(MA.ANNEE) AS ANNEE
FROM
    MOIS_ANNEE       MA
    LEFT JOIN COMMANDE C
    ON EXTRACT(YEAR FROM C.DATE_COMMANDE) = MA.ANNEE
    LEFT JOIN COMMANDE_PRODUIT CP
    ON CP.ID_COMMANDE = C.ID
    LEFT JOIN PRODUIT P
    ON CP.ID_PRODUIT = P.ID
WHERE
    CP.STATUS_COMMANDE >= 1
    AND P.ID_PERSONNE = 1
    OR C.ID IS NULL
GROUP BY
    MA.ANNEE
ORDER BY
    MA.ANNEE;

-- MODIFICATION DU MONTANT TOTAL DANS COMMANDE (SANS TVA)
UPDATE COMMANDE C
SET
    MONTANT_TOTAL = (
        SELECT
            SUM(CP.PRIX_UNITAIRE * CP.QUANTITE)
        FROM
            COMMANDE_PRODUIT CP
        WHERE
            CP.ID_COMMANDE = C.ID
    )
WHERE
    C.ID IN (
        SELECT
            DISTINCT ID_COMMANDE
        FROM
            COMMANDE_PRODUIT
    );

SELECT
    PP.ID_PANIER,
    PE.ID                                                                                     AS ID_VENDEUR,
    COALESCE(SUM(P.PRIX * PP.QUANTITE), 0)                                                    AS PRIX_HT,
    (COALESCE(SUM(P.PRIX * PP.QUANTITE), 0) * 0.2)                                            AS PRIX_TVA,
    (COALESCE(SUM(P.PRIX * PP.QUANTITE), 0) + (COALESCE(SUM(P.PRIX * PP.QUANTITE), 0) * 0.2)) AS PRIX_TTC
FROM
    PRODUIT_PANIER PP
    JOIN PRODUIT P
    ON P.ID = PP.ID_PRODUIT
    JOIN PERSONNE PE
    ON PE.ID = P.ID_PERSONNE
WHERE
    PP.ID_PANIER = ?
GROUP BY
    PP.ID_PANIER,
    PE.ID;

SELECT
    P.ID AS ID_PERSONNE,
    P.NOM AS NOM_PERSONNE,
    P.PRENOM AS PRENOM_PERSONNE,
    P.CODE_POSTAL AS CODE_POSTAL,
    P.CONTACT AS CONTACT,
    P.LOCALISATION AS LOCALISATION,
    P.ID_ROLE AS ID_ROLE,
    COALESCE(P.ID_TYPE_PRODUCTION,
    0) AS ID_TYPE_PRODUCTION,
    P.DATE_NAISSANCE AS DATE_NAISSANCE,
    U.ID AS ID_UTILISATEUR,
    U.EMAIL AS EMAIL,
    U.PSEUDO AS PSEUDO,
    U.DATE_INSCRIPTION AS DATE_INSCRIPTION
FROM
    PERSONNE P
    JOIN UTILISATEUR U
    ON U.ID = P.ID_UTILISATEUR
WHERE
    U.IS_ADMIN = 0 LIMIT ? OFFSET ?;